### ISSUE TITLE
vietnam mode doesn't appear to be working

### ISSUE THREAD

**Issue by jamesla** [jkuettner/bfbc2-server#5]
Hey @jkuettner 

Thanks for making this it's been really helpful.

I've noticed that vietnam sqdm mode is not working - the server works fine but it just creates a regular sqdm server instead of vietnam mode.

Is there anything else that I need to do to make it work?

Fully working docker-compose file below - to reproduce just start it and when you connect it will be a regular sqdm server.

```yaml
  bc2-master-server:
    image: quay.io/docker-gameserver/bfbc2-master-server
    network_mode: host
    restart: always
    tty: true
  bc2-viet-sqdm:
    image: quay.io/docker-gameserver/bfbc2-server
    restart: always
    network_mode: host
    environment:
      MASTER_SERVER: localhost
      SERVER_TYPE: vietsqdm
      SERVER_NAME: Lancation squaddm
      SERVER_PORT: 19567
      SERVER_ADMIN_PORT: 48888
      SERVER_ADMIN_PASSWORD: "" 
      SERVER_MAX_PLAYERS: 16
      SERVER_HARDCORE: false
      SERVER_FF: true
      SERVER_TEAMBALANCE: true
      SERVER_KILLCAM: true
      SERVER_MINIMAP: false
      SERVER_CROSSHAIR: true
      SERVER_SPOTTING: true
      SERVER_MINIMAP_SPOTTING: false
    depends_on:
      - bc2-master-server
```
